[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheckPath]
path = "/api/health"

[deploy.variables]
NODE_ENV = "production"